# Generated by Django 3.1.3 on 2020-11-23 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa_medica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_nombre', models.CharField(max_length=255)),
                ('medicamento_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamento_casa', to='farmacia.casamedica')),
                ('medicamento_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamento_proveedor', to='farmacia.proveedor')),
            ],
        ),
    ]
